add generic type param for SelfDescribing (closes #156)
snowplow-incubator/snowplow-react-native-tracker pull request #158
Opened 2022-03-04 16:17 UTC by henbrand

2022-03-07 10:15 UTC, AlexBenny commented
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

2022-03-07 10:20 UTC, henbrand commented
signed!

2022-03-07 10:32 UTC, AlexBenny commented
Confirmed! @henbrand  has signed the Contributor License Agreement. Thanks so much.

2022-03-07 13:01 UTC, matus-tomlein requested changes
Thanks for the PR @henbrand!

It looks good, I just noted one issue with the type for `trackSelfDescribingEvent` that I think should reflect the one used in `SelfDescribing`.

2022-03-07 13:01 UTC, matus-tomlein commented on src/types.ts
> +  readonly trackSelfDescribingEvent: <TData extends Record<string, unknown>>(
I think that the generic type should match the generic type used for data in the `SelfDescribing` type, i.e., `TData extends Record<keyof TData, unknown> = Record<string, unknown>`.

2022-03-07 13:34 UTC, henbrand commented on src/types.ts
> +  readonly trackSelfDescribingEvent: <TData extends Record<string, unknown>>(
updated!

2022-03-08 08:17 UTC, matus-tomlein approved these changes
LGTM!

2022-03-08 08:17 UTC, matus-tomlein commented on src/types.ts
> +
```suggestion
```

This is a small nitpick, but there shouldn't be a blank line between the comment and the definition it belongs to.

2022-03-08 15:05 UTC, henbrand commented on src/types.ts
> +
updated!

2022-03-09 07:29 UTC, merged